### ISSUE TITLE
Do you have a plan to rewrite this project in tensorflow?

### ISSUE THREAD

**Issue by xray1111** [ldeecke/vae-torch#1]
I'm wandering if it could be true, cause I only know some tensorflow stuff...

**Comment by ldeecke** [comment]
To my knowledge, a number of good implementations already exist, see e.g. [Jan Hendrik Metzen's blog](https://jmetzen.github.io/2015-11-27/vae.html).

So no, at the moment I hadn't planned to implement this in tensorflow.
