### ISSUE TITLE
requirements of environment

### ISSUE THREAD

**Issue by Baileyswu** [ldeecke/vae-torch#2]
Hi, I run your code in annaconda but failed. I speculate that my package version is different with yours. 

```
# Name                    Version                   Build  Channel
torch                     1.3.0                     <pip>
torchvision               0.4.1                     <pip>
```

could you offer your environment in this folder like [this](https://github.com/altosaar/variational-autoencoder/blob/master/environment.yml)?

**Comment by ldeecke** [comment]
Also ran into an issue with above specifications. Should be fixed now.
